<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */
// Disabled layout
$this->layout()->disableLayout();
?>
<div class="notification"><?php echo $this->translate('report_is_created', $this->ReportName);?></div>
<table>
<?php
echo $this->Action('list', 'report', null, array(
                'CustomerAccountId' => $this->CustomerAccountId,
                'CurrentPage' => $this->Pagination['CurrentPage'],
                'ItemsPerPage' => $this->Pagination['ItemsPerPage']
            ));
?>
</table>
<?php
/* EOF */