<?php
/**
 * $Rev: 1974 $
 * $LastChangedDate: 2010-04-08 12:50:29 +0800 (Thu, 08 Apr 2010) $
 * $LastChangedBy: yaoli $
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id: list.phtml 1974 2010-04-08 04:50:29Z yaoli $
 */
$baseUrl = rtrim($this->BaseUrl(), '/') . '/report';
$this->ListUrl = $baseUrl . '/list/';
$this->CurrentCount = count($this->Reports);
?>
<tfoot>
    <tr>
        <td colspan="8">
            <?php
            echo $this->render('pagination.phtml');
            ?>
        </td>
    </tr>
</tfoot>
<tbody>
<?php
    if ($this->CurrentCount) {
        $count = 0;
        foreach ($this->Reports as $report) {
?>
            <tr id="row-item-<?php echo $report['ReportId']?>" class="row-item<?php echo ($count++%2 ? ' leaper' : '') ;?>">
                <td class="column-1"><input type="checkbox"/></td>
                <td class="column-2" title="<?php echo $report['ReportName']?>">
                    <span><?php echo $report['ReportName']?></span>
                    <div class="manager">
                        <a class="manager-edit" title="<?php echo $this->translate('application_handler_edit')?>"
                        href="<?php echo $baseUrl?>/update/ReportId/<?php echo $report['ReportId']?>"><?php
                            echo $this->translate('application_handler_edit')?></a>|<a class="manager-delete"
                            title="<?php echo $this->translate('application_handler_delete')?>"
                        href="<?php echo $baseUrl?>/delete?ReportIds[]=<?php echo $report['ReportId']?>&ReportNames[]=<?php
                            echo urlencode($report['ReportName'])?>"><?php echo $this->translate('application_handler_delete')?></a>
                    </div>
                </td>
                <td class="column-3" title="<?php echo $report['ReportType']?>">
                    <span><?php echo $report['ReportType']?></span>
                </td>
                <td class="column-4" title="<?php echo $report['CreationDatetime']?>">
                    <span><?php echo $report['CreationDatetime']?></span>
                </td>
                <td class="column-5" title="<?php echo $report['ModificationDatetime']?>">
                    <span><?php echo $report['ModificationDatetime']?></span>
                </td>
                <td class="column-6" title="<?php echo $report['CustomerUserName']?>">
                    <span><?php echo $report['CustomerUserName']?></span>
                </td>
                <td class="column-7" title="<?php echo $report['ReportName']?>">
                    <span><?php echo $report['ReportName']?></span>
                </td>
                <td class="column-0">
                    <span><?php echo $report['ReportFormat']?></span>
                </td>
            </tr>
<?php
        }
    } else {
?>
        <tr class="row-item-none">
            <td colspan="8"><span><?php echo $this->translate('report_list_no_item')?></span></td>
        </tr>
<?php } ?>
</tbody>
<?php
/* EOF */
