<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */

// Disabled layout
$this->layout()->disableLayout();
$baseUrl = rtrim($this->BaseUrl(), '/') . '/report';
?>
<div class="notification"><?php echo $this->translate('report_is_updated', $this->Report['ReportName']);?></div>
<table>
    <tr>
        <td class="column-1"><input type="checkbox"/></td>
        <td class="column-2" title="<?php echo $this->Report['ReportName']?>">
            <span><?php echo $this->Report['ReportName']?></span>
            <div class="manager">
                <a class="manager-edit" title="<?php echo $this->translate('application_handler_edit')?>"
                href="<?php echo $baseUrl?>/update/ReportId/<?php echo $this->Report['ReportId']?>"><?php
                    echo $this->translate('application_handler_edit')?></a>|<a class="manager-delete"
                    title="<?php echo $this->translate('application_handler_delete')?>"
                href="<?php echo $baseUrl?>/delete?ReportIds[]=<?php echo $this->Report['ReportId']?>&ReportNames[]=<?php
                    echo urlencode($this->Report['ReportName'])?>"><?php echo $this->translate('application_handler_delete')?></a>
            </div>
        </td>
        <td class="column-3" title="<?php echo $this->Report['ReportType']?>">
            <span><?php echo $this->Report['ReportType']?></span>
        </td>
        <td class="column-4" title="<?php echo $this->Report['CreationDatetime']?>">
            <span><?php echo $this->Report['CreationDatetime']?></span>
        </td>
        <td class="column-5" title="<?php echo $this->Report['ModificationDatetime']?>">
            <span><?php echo $this->Report['ModificationDatetime']?></span>
        </td>
        <td class="column-6" title="<?php echo $this->Report['CustomerUserName']?>">
            <span><?php echo $this->Report['CustomerUserName']?></span>
        </td>
        <td class="column-7" title="<?php echo $this->Report['ReportName']?>">
            <span><?php echo $this->Report['ReportName']?></span>
        </td>
        <td class="column-0">
            <span><?php echo $this->Report['ReportFormat']?></span>
        </td>
    </tr>
</table>
<?php
/* EOF */