<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */

// Disabled layout
$this->layout()->disableLayout();
$baseUrl = rtrim($this->BaseUrl(), '/') . '/calendar';
?>
<div class="notification"><?php echo $this->translate('calendar_is_updated', $this->Calendar['Label']);?></div>
<table>
  <tr>
    <td class="column-1"><input type="checkbox"/></td>
    <td class="column-2" title="<?php echo $this->Calendar['Label']?>">
        <span><?php echo $this->Calendar['Label']?></span>
        <div class="manager">
            <a class="manager-edit" title="<?php echo $this->translate('application_handler_edit')?>"
            href="<?php echo $baseUrl?>/update/CalendarId/<?php echo $this->Calendar['CalendarId']?>"><?php
                echo $this->translate('application_handler_edit')?></a>|<a class="manager-delete"
                title="<?php echo $this->translate('application_handler_delete')?>"
            href="<?php echo $baseUrl?>/delete?CalendarIds[]=<?php echo $this->Calendar['CalendarId']?>&Labels[]=<?php
                echo urlencode($this->Calendar['Label'])?>"><?php echo $this->translate('application_handler_delete')?></a>
        </div>
    </td>
    <td class="column-3" title="<?php echo $this->translate('calendar_type_' . $this->Calendar['CalendarTypeId'])?>">
        <span><?php echo $this->translate('calendar_type_' . $this->Calendar['CalendarTypeId'])?></span>
    </td>
    <td class="column-4" title="<?php echo $this->Calendar['CreationDatetime']?>">
        <span><?php echo $this->Calendar['CreationDatetime']?></span>
    </td>
    <td class="column-5" title="<?php echo $this->Calendar['ModificationDatetime']?>">
        <span><?php echo $this->Calendar['ModificationDatetime']?></span>
    </td>
    <td class="column-6" title="<?php echo $this->Calendar['CustomerUserName']?>">
        <span><?php echo $this->Calendar['CustomerUserName']?></span>
    </td>
    <td class="column-0">
        <span class="resource_<?php echo ($this->Calendar['ReferenceCounter']>0 ? 'in':'not')?>_use">&nbsp;</span>
    </td>
  </tr>
</table>
<?php
/* EOF */