<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Lance LI <yaoli@streamwide.com>
 * @version    $Id$
 */

// Disabled layout
$this->layout()->disableLayout();
?>
<div class="notification" routingplan="<?php echo $this->RoutingPlanId;?>"><?php echo $this->translate('allocatedtree_is_created');?></div>
<?php
/* EOF */