<?php
/**
 * $Rev: 1974 $
 * $LastChangedDate: 2010-04-08 12:50:29 +0800 (Thu, 08 Apr 2010) $
 * $LastChangedBy: yaoli $
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id: list.phtml 1974 2010-04-08 04:50:29Z yaoli $
 */
$baseUrl = rtrim($this->BaseUrl(), '/') . '/numbergroup';
$this->ListUrl = $baseUrl . '/list/';
$this->CurrentCount = count($this->PremiumNumberGroups);
?>
<tfoot>
    <tr>
        <td colspan="8">
            <?php
            echo $this->render('pagination.phtml');
            ?>
        </td>
    </tr>
</tfoot>
<tbody>
<?php
    if ($this->CurrentCount) {
        $count = 0;
        foreach ($this->PremiumNumberGroups as $premiumNumberGroup) {
?>
            <tr id="row-item-<?php echo $premiumNumberGroup['PremiumNumberGroupId']?>" class="row-item<?php echo ($count++%2 ? ' leaper' : '') ;?>">
                <td class="column-1"><input type="checkbox"/></td>
                <td class="column-2" title="<?php echo $premiumNumberGroup['PremiumNumberGroupName']?>">
                    <span><?php echo $premiumNumberGroup['PremiumNumberGroupName']?></span>
                    <div class="manager">
                        <a class="manager-edit" title="<?php echo $this->translate('application_handler_edit')?>"
                        href="<?php echo $baseUrl?>/update/PremiumNumberGroupId/<?php echo $premiumNumberGroup['PremiumNumberGroupId']?>"><?php
                            echo $this->translate('application_handler_edit')?></a>|<a class="manager-delete"
                            title="<?php echo $this->translate('application_handler_delete')?>"
                        href="<?php echo $baseUrl?>/delete?PremiumNumberGroupIds[]=<?php echo $premiumNumberGroup['PremiumNumberGroupId']?>&PremiumNumberGroupNames[]=<?php
                            echo urlencode($premiumNumberGroup['PremiumNumberGroupName'])?>"><?php echo $this->translate('application_handler_delete')?></a>
                    </div>
                </td>
                <td class="column-3" title="<?php echo $this->translate('solution_type_' . $premiumNumberGroup['SolutionTypeId']);?>">
                    <span><?php echo $this->translate('solution_type_' . $premiumNumberGroup['SolutionTypeId']);?></span>
                </td>
                <td class="column-4" title="<?php echo $premiumNumberGroup['TemplateTreeLabel']?>">
                    <span><?php echo $premiumNumberGroup['TemplateTreeLabel']?></span>
                </td>
                <td class="column-5" title="<?php echo $premiumNumberGroup['CreationDatetime']?>">
                    <span><?php echo $premiumNumberGroup['CreationDatetime']?></span>
                </td>
                <td class="column-6" title="<?php echo $premiumNumberGroup['ModificationDatetime']?>">
                    <span><?php echo $premiumNumberGroup['ModificationDatetime']?></span>
                </td>
                <td class="column-7" title="<?php echo $premiumNumberGroup['CustomerUserName']?>">
                    <span><?php echo $premiumNumberGroup['CustomerUserName']?></span>
                </td>
                <td class="column-0">
                    <span class="<?php echo ($premiumNumberGroup['EmergencyActivated'] > 0 ? 'active':'unactive')?>">&nbsp;</span>
                </td>
            </tr>
<?php
        }
    } else {
?>
        <tr class="row-item-none">
            <td colspan="8"><span><?php echo $this->translate('numbergroup_list_no_item')?></span></td>
        </tr>
<?php } ?>
</tbody>
<?php
/* EOF */