<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */

// Disabled layout
$this->layout()->disableLayout();
$baseUrl = rtrim($this->BaseUrl(), '/') . '/media';
?>
<div class="notification"><?php echo $this->translate('media_is_updated', $this->Prompt['PromptName']);?></div>
<table>
    <tr>
        <td class="column-1">
            <input type="checkbox" name="media_list[]" value="<?php echo $this->Prompt['PromptId']?>"/></p>
        </td>
        <td class="column-2">
            <span><?php echo $this->Prompt['PromptName']?></span>
            <div class="manager">
                <a class="manager-edit" href="<?php echo $baseUrl?>/update/PromptId/<?php echo $this->Prompt['PromptId']?>">
                    <?php echo $this->translate('application_handler_edit')?>
                </a> | <a class="manager-delete" href="<?php echo $baseUrl?>/delete?PromptIds[]=<?php echo $this->Prompt['PromptId']?>&PromptNames[]=<?php
                    echo urlencode($this->Prompt['PromptName'])?>"><?php echo $this->translate('application_handler_delete')?>
                </a>
            </div>
        </td>
        <td class="column-3" title="<?php echo $this->Prompt['FileName']?>">
            <span class="listen">LISTEN</span>
        </td>
        <td class="column-4" title="<?php echo $this->Prompt['FileSize']?>">
            <span><?php echo $this->Prompt['FileSize']?></span>
        </td>
        <td class="column-5" title="<?php echo $this->Prompt['CreationDatetime']?>">
            <span><?php echo $this->Prompt['CreationDatetime']?></span>
        </td>
        <td class="column-6" title="<?php echo $this->Prompt['ModificationDatetime']?>">
            <span><?php echo $this->Prompt['ModificationDatetime']?></span>
        </td>
        <td class="column-7" title="<?php echo $this->Prompt['CustomerUserName']?>">
            <span><?php echo $this->Prompt['CustomerUserName']?></span>
        </td>
        <td class="column-0">
            <span class="resource_<?php echo ($this->Prompt['ReferenceCounter'] > 0 ? 'in':'not')?>_use">&nbsp;</span>
        </td>
    </tr>
</table>
<?php
/* EOF */