<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    modules_default
 * @subpackage views_scripts_account
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Lance LI<yaoli@streamwide.com>
 * @version    $Id$
 */
// Disabled layout
$this->layout()->disableLayout();
?>
<div class="notification"><?php echo $this->translate('agentgroup_group_is_updated', $this->OldAgentGroupName);?></div>
      <table>
          <tr class="list_item" itemId="<?php echo $this->AgentgroupId?>">
            <td class="agent_group_name" groupId="<?php echo $this->AgentgroupId?>">
              <?php echo $this->AgentGroupName?>
            </td>
            <td class="agent_count">0</td>
          </tr>
      </table>
<?php
/* EOF */
