<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    modules_default
 * @subpackage views_scripts_account
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Lance LI<yaoli@streamwide.com>
 * @version    $Id$
 */
// Disabled layout
$this->layout()->disableLayout();
?>
<div class="notification" unaffected="<?php echo $this->CountUnaffectedAgents?>"><?php echo $this->translate('agentgroup_group_is_deleted', $this->AgentGroupName);?></div>
<?php
/* EOF */
