<?php
/**
 * $Rev: 2032 $
 * $LastChangedDate: 2010-05-06 17:46:09 +0800 (Thu, 06 May 2010) $
 * $LastChangedBy: junzhang $
 *
 * @category   application
 * @package    modules_default
 * @subpackage views_scripts_index
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     James ZHANG <junzhang@streamwide.com>
 * @version    $Id: index.phtml 2032 2010-05-06 09:46:09Z junzhang $
 */
?>
<div id="homepage">
<?php 
    // TODO code the home page, debug first
    echo $this->translate('application_title_product'); 
?>
</div>
<?php
/* EOF */