<?php
/**
 * $Rev: 1746 $
 * $LastChangedDate: 2010-03-23 18:46:26 +0800 (Tue, 23 Mar 2010) $
 * $LastChangedBy: zwang $
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id: index.phtml 1746 2010-03-23 10:46:26Z zwang $
 */

$baseUrl = rtrim($this->BaseUrl(), '/');

$this->headLink()->appendStylesheet($baseUrl . '/styles/resource.css')
                 ->appendStylesheet($baseUrl . '/styles/customer.css')
                 ->appendStylesheet($baseUrl . '/styles/jquery-tablesorter.css');
$this->headScript()->appendFile($baseUrl . '/js/resource.js')
                   ->appendFile($baseUrl . '/js/customer.js')
                   ->appendFile($baseUrl . '/js/jquery-metadata.js')
                   ->appendFile($baseUrl . '/js/jquery-tablesorter.js');

?>
<div class="grid_2 prefix_1 oops-container">
    <div id="left_menu" class="left_menu">
        <a href="<?php echo $baseUrl?>/customer/list" class="list-refresh sw-button on">
            <?php echo $this->translate('left_menu_customer')?>
        </a>
        <a href="<?php echo $baseUrl?>/customer/create" class="sw-button only-popup" id="create">
            <?php echo $this->translate('left_menu_add_customer')?>
        </a>
    </div>
</div>

<div class="grid_12 suffix_1 oops-container">
    <div id="customers" class="list-container">
        <div class="list-content">
            <table>
                <tbody>
                    <tr>
                        <td>
                            <div class="list-header">
                                <table>
                                    <tbody>
                                        <tr>
                                            <td>
                                                <div class="list-header-below"><span class="icon-below">&nbsp;</span></div>
                                                <div class="list-header-batch-delete">
                                                    <button type="button" id="delete" class="batch-delete">
                                                    <?php echo $this->translate('application_handler_batch_delete')?>
                                                    </button>
                                                </div>
                                                <div class="search-box" >
                                                    <form action="<?php echo $baseUrl, '/customer/list'?>">
                                                        <div class="search-box-input">
                                                            <div class="search-icon">&nbsp;</div>
                                                            <input type="text" name="CustomerAccountNamePart" class="keyword input_default"
                                                            value="<?php echo $this->translate('application_handler_search_input')?>"/>
                                                        </div>
                                                        <button class="search" type="submit">
                                                        <?php echo $this->translate('application_handler_ok')?></button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div id="customer-list" class="list-body">
                                <table>
                                    <thead>
                                        <tr>
                                            <th class="column-1"><div><input type="checkbox" class="checkbox-switch"/></div></th>
                                            <th class="column-2" title="<?php echo $this->translate('customer_list_accountName')?>">
                                                <span><?php echo $this->translate('customer_list_accountName')?></span>
                                            </th>
                                            <th class="column-3" title="<?php echo $this->translate('customer_list_billingId')?>">
                                                <span><?php echo $this->translate('customer_list_billingId')?></span>
                                            </th>
                                            <th class="column-4" title="<?php echo $this->translate('customer_list_customerName')?>">
                                                <span><?php echo $this->translate('customer_list_customerName')?></span>
                                            </th>
                                            <th class="column-5" title="<?php echo $this->translate('customer_list_customerEmail')?>">
                                                <span><?php echo $this->translate('customer_list_customerEmail')?></span>
                                            </th>
                                            <th class="column-0" title="<?php echo $this->translate('customer_list_customerPhone')?>">
                                                <span><?php echo $this->translate('customer_list_customerPhone')?></span>
                                            </th>
                                        </tr>
                                    </thead>
                                    <?php
                                    echo $this->render('customer/list.phtml');
                                    ?>
                                </table>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
var LOCAL = "<?php echo $baseUrl, '/customer/'?>";
</script>
<?php
/* EOF */