<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */

// Disabled layout
$this->layout()->disableLayout();
$baseUrl = rtrim($this->BaseUrl(), '/') . '/customer';
?>
<div class="notification"><?php echo $this->translate('customer_is_updated', $this->CustomerAccount['CustomerAccountName']);?></div>
<table>
    <tr>
        <td class="column-1">
            <input type="checkbox" name="customerAccount_list[]" value="<?php echo $this->CustomerAccount['CustomerAccountId']?>"/></p>
        </td>
        <td class="column-2">
            <span><?php echo $this->CustomerAccount['CustomerAccountName']?></span>
            <div class="manager">
                <a class="manager-edit" href="<?php echo $baseUrl?>/update/CustomerAccountId/<?php echo $this->CustomerAccount['CustomerAccountId']?>">
                    <?php echo $this->translate('application_handler_edit')?>
                </a> | <a class="manager-delete" href="<?php echo $baseUrl?>/delete?CustomerAccountIds[]=<?php echo $this->CustomerAccount['CustomerAccountId']?>&CustomerAccountNames[]=<?php
                    echo urlencode($this->CustomerAccount['CustomerAccountName'])?>"><?php echo $this->translate('application_handler_delete')?>
                </a>
            </div>
        </td>
        <td class="column-3" title="">
            <span><?php echo $this->CustomerAccount['CustomerAccountBillingId']?></span>
        </td>
        <td class="column-4" title="">
            <span><?php echo $this->CustomerAccount['ContactName']?></span>
        </td>
        <td class="column-5" title="">
            <span><?php echo $this->CustomerAccount['ContactEmail']?></span>
        </td>
        <td class="column-6" title="">
            <span><?php echo $this->CustomerAccount['ContactPhone']?></span>
        </td>
        <td class="column-7" title="">
            <span><?php echo $this->CustomerAccount['CreationDateTime']?></span>
        </td>
        <td class="column-0" title="">
            <span><?php echo $this->CustomerAccount['']?></span>
        </td>
    </tr>
</table>
<?php
/* EOF */