<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    modules_default
 * @subpackage views_scripts_account
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Lance LI<yaoli@streamwide.com>
 * @version    $Id$
 */
// Disabled layout
$this->layout()->disableLayout();
?>
<div class="notification"><?php echo $this->translate('blacklist_number_is_deleted', $this->DeletedPhoneNumbers);?></div>
<?php
echo $this->Action('listnumber', 'blacklist', null, array(
                'BlacklistId' => $this->BlacklistId
            ));
/* EOF */
