<?php
/**
 * $Rev: 1974 $
 * $LastChangedDate: 2010-04-08 12:50:29 +0800 (Thu, 08 Apr 2010) $
 * $LastChangedBy: yaoli $
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id: list.phtml 1974 2010-04-08 04:50:29Z yaoli $
 */

$translate = Streamwide_Web_Translate::functor();

$baseUrl = rtrim($this->BaseUrl(), '/') . '/blacklist';

?>
<div id="main_content">
  <div id="main_content_container">
     Oops,we has no time to do this page!
  </div>
</div>
<?php
/* EOF */