<?php
/**
 * $Rev:  $
 * $LastChangedDate:  $
 * $LastChangedBy: yaoli $
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id: list.phtml $
 */

$baseUrl = rtrim($this->BaseUrl(), '/') . '/admin';
$this->ListUrl = $baseUrl . '/list/';
$this->CurrentCount = count($this->Users);

?>
<tfoot>
    <tr>
        <td colspan="8">
            <?php
            echo $this->render('pagination.phtml');
            ?>
        </td>
    </tr>
</tfoot>
<tbody>
<?php
    if ($this->CurrentCount) {
        $count = 0;
        foreach ($this->Users as $user) {
?>
            <tr id="row-item-<?php echo $user['UserId']?>" class="row-item<?php echo ($count++%2 ? ' leaper' : '') ;?>">
                <td class="column-1"><input type="checkbox"/></td>
                <td class="column-2" title="<?php echo $user['Name']?>">
                    <span><?php echo $user['Name']?></span>
                    <div class="manager">
                        <a class="manager-edit" title="<?php echo $this->translate('application_handler_edit')?>"
                        href="<?php echo $baseUrl?>/update/UserId/<?php echo $user['UserId']?>"><?php
                            echo $this->translate('application_handler_edit')?></a>|<a class="manager-delete"
                            title="<?php echo $this->translate('application_handler_delete')?>"
                        href="<?php echo $baseUrl?>/delete?UserIds[]=<?php echo $user['UserId']?>&UserNames[]=<?php
                            echo urlencode($user['Name'])?>"><?php echo $this->translate('application_handler_delete')?></a>
                    </div>
                </td>
                <td class="column-3" title="<?php echo $user['CustomerAccountName']?>">
                    <span><?php echo $user['CustomerAccountName']?></span>
                </td>
                <td class="column-4" title="<?php echo $user['EmailAddress']?>">
                    <span><?php echo $user['EmailAddress']?></span>
                </td>
                <td class="column-5" title="<?php echo $user['ProfileLabel']?>">
                    <span><?php echo $user['ProfileLabel']?></span>
                </td>
                <td class="column-6" title="<?php echo $user['ParentUserName']?>">
                    <span><?php echo $user['ParentUserName']?></span>
                </td>
                <td class="column-7" title="<?php echo $user['LastLoginDatetime']?>">
                    <span><?php echo $user['LastLoginDatetime']?></span>
                </td>
                <td class="column-0">
                    <span class="resource_<?php echo ($this->User['IsLocked']>0 ? 'in':'not')?>_use">&nbsp;</span>
                </td>
            </tr>
<?php
        }
    } else {
?>
        <tr class="row-item-none">
            <td colspan="8"><span><?php echo $this->translate('admin_list_no_item')?></span></td>
        </tr>
<?php } ?>
</tbody>
<?php
/* EOF */
