<?php
/**
 * $Rev: 1974 $
 * $LastChangedDate: 2010-04-08 12:50:29 +0800 (Thu, 08 Apr 2010) $
 * $LastChangedBy: yaoli $
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id: list.phtml 1974 2010-04-08 04:50:29Z yaoli $
 */

$baseUrl = rtrim($this->BaseUrl(), '/') . '/trunk';
$this->ListUrl = $baseUrl . '/list/';
$this->CurrentCount = count($this->Trunks);
?>
<tfoot>
    <tr>
        <td colspan="4">
            <?php
            echo $this->render('pagination.phtml');
            ?>
        </td>
    </tr>
</tfoot>
<tbody>
    <?php
        if ($this->CurrentCount > 0) {
            $count = 0;
            foreach($this->Trunks as $trunk) {
    ?>
    <tr id="row-item-<?php echo $trunk['TrunkId']?>" class="row-item <?php echo $count++%2 ? 'leaper' : ''?>">
        <td class="column-1"><input type="checkbox"/></td>
        <td class="column-2" title="<?php echo $trunk['Label']?>">
            <span><?php echo $trunk['Label']?></span>
            <div class="manager">
                <a href="<?php echo $baseUrl?>/update/TrunkId/<?php echo $trunk['TrunkId']?>" 
                    class="manager-edit" title="<?php echo $this->translate('application_handler_edit')?>">
                    <?php echo $this->translate('application_handler_edit')?></a>|
                <a href="<?php echo $baseUrl?>/delete?TrunkIds[]=<?php echo $trunk['TrunkId']?>&TrunkLabels[]=
                    <?php echo urlencode($trunk['Label'])?>" class="manager-delete" 
                    title="<?php echo $this->translate('application_handler_delete')?>">
                    <?php echo $this->translate('application_handler_delete')?></a>
            </div>
        </td>
        <td class="column-3" title="<?php echo $trunk['ExternalId']?>">
            <span><?php echo $trunk['ExternalId']?></span>
        </td>
        <td class="column-0" title="<?php echo $trunk['IpAddress']. ':'. $trunk['Port']?>">
            <span><?php echo $trunk['IpAddress']. ':'. $trunk['Port']?></span>
        </td>
    </tr>
    <?php 
            }
        } else {
    ?>
        <tr class="row-item-none">
            <td colspan="4"><span><?php echo $this->translate('trunk_list_no_item')?></span></td>
        </tr> 
    <?php
        }
    ?>
</tbody>
<?php 
/* EOF */