<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */

// Disabled layout
$this->layout()->disableLayout();
$baseUrl = rtrim($this->BaseUrl(), '/') . '/trunk';
?>
<div class="notification"><?php echo $this->translate('trunk_is_updated', $this->Trunk['Label']);?></div>
<table>
    <tr>
        <td class="column-1">
            <input type="checkbox" name="trunk_list[]" value="<?php echo $this->Trunk['TrunkId']?>"/></p>
        </td>
        <td class="column-2">
            <span><?php echo $this->Trunk['Label']?></span>
            <div class="manager">
                <a class="manager-edit" href="<?php echo $baseUrl?>/update/TrunkId/<?php echo $this->Trunk['TrunkId']?>">
                    <?php echo $this->translate('application_handler_edit')?>
                </a> | <a class="manager-delete" href="<?php echo $baseUrl?>/delete?TrunkIds[]=<?php echo $this->Trunk['TrunkId']?>&TrunkLabels[]=<?php
                    echo urlencode($this->Trunk['Label'])?>"><?php echo $this->translate('application_handler_delete')?>
                </a>
            </div>
        </td>
        <td class="column-3" title="">
            <span><?php echo $this->Trunk['ExternalId']?></span>
        </td>
        <td class="column-0" title="">
            <span><?php echo $this->Trunk['IpAddress']. ':'. $this->Trunk['Port']?></span>
        </td>
    </tr>
</table>
<?php
/* EOF */