<?php
/**
 * $Rev: 2390 $
 * $LastChangedDate: 2010-06-02 17:40:19 +0800 (Wed, 02 Jun 2010) $
 * $LastChangedBy: junzhang $
 *
 * @category   application
 * @package    modules_default
 * @subpackage view_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     James ZHANG <junzhang@streamwide.com>
 * @version    $Id: cell.phtml 2390 2010-06-02 09:40:19Z junzhang $
 */

/**
 * After removed a NodeOutput, responsed a notification to browser
 */
echo $this->result;
/* EOF */