<?php
/**
 * $Rev: 2653 $
 * $LastChangedDate: 2010-06-23 12:06:53 +0800 (Wed, 23 Jun 2010) $
 * $LastChangedBy: junzhang $
 *
 * @category   application
 * @package    modules_default
 * @subpackage view_scripts_node
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     James ZHANG <junzhang@streamwide.com>
 * @version    $Id: create-ack.phtml 2653 2010-06-23 04:06:53Z junzhang $
 */

echo '<div id="notification"> ',
    $this->translate('node_create_success', array($this->Label)),
    ' </div>';

/* EOF */