<?php
/**
 * $Rev: 2661 $
 * $LastChangedDate: 2010-06-23 17:36:49 +0800 (Wed, 23 Jun 2010) $
 * $LastChangedBy: junzhang $
 *
 * @category   application
 * @package    modules_default
 * @subpackage views_scripts_node
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     James ZHANG <junzhang@streamwide.com>
 * @version    $Id: link.phtml 2661 2010-06-23 09:36:49Z junzhang $
 */

/**
 * Modal Window for Node Link in a HTML version
 */

$isUpdating = is_array($this->Node);
$nodeName = $isUpdating ? $this->Node['Label'] : $this->translate('dialog_form_node_label_default');
$linkedNodeId = $isUpdating ? $this->NodeParameter['LinkedNodeId'] : '';
$queryNodeLabel = '';
if ($isUpdating && $this->NodeParameter['IsInternal']) {
    foreach($this->Nodes as $item) {
        if ($linkedNodeId == $item['NodeId']) {
            $queryNodeLabel = $item['Label'];
            break;
        }
    }
}
?>
<div class="dialog" id="link-dialog">
    <form id="form-node-link" method="post" enctype="application/x-www-form-urlencoded">
        <div class="dialog-content">
            <div class="dialog-heading" id="link-heading">
                <span class="heading-text"><?php echo $this->translate('dialog_heading_node_link'); ?></span>
                <span class="heading-close"><?php echo $this->translate('application_handler_close'); ?></span>
                <div class="heading-switcher">
                    <table>
                        <tr>
                            <td>
                                <div class="heading-switcher-on">
                                    <input type="radio" name="IsActive" value="1"<?php echo (!$isUpdating || $this->Node['IsActive']) ? ' checked="checked"' : ''; ?> />
                                    <?php echo $this->translate('dialog_heading_node_active'); ?>
                                </div>
                            </td>
                            <td>
                                <span class="heading-switcher-spacer">&nbsp;</span>
                            </td>
                            <td>
                                <div class="heading-switcher-off">
                                    <input type="radio" name="IsActive" value="0"<?php echo ($isUpdating && !$this->Node['IsActive']) ? ' checked="checked"' : ''; ?> />
                                    <?php echo $this->translate('dialog_heading_node_deactive'); ?>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="dialog-body" id="link-body">
                <div class="description tips"><?php echo $this->translate('dialog_heading_node_link_description'); ?></div>
                <div>
                    <label for="Label" class="block">
                        <?php echo $this->translate('dialog_form_node_label', array( $this->translate('tree_node_type_link') )); ?>
                    </label>
                    <input type="text" class="input_default" id="Label" name="Label" value="<?php echo $nodeName; ?>" />
                    <span class="tips"> 
                        <?php echo $this->translate('dialog_form_node_label_description', array( $this->translate('tree_node_type_link') )); ?>
                    </span>
                </div>
                <table width="100%">
                    <tr>
                        <td width="20%">
                            <div>
                                <input type="radio" id="IsInternal-1" name="IsInternal" value="1"<?php echo (!$isUpdating || $this->NodeParameter['IsInternal']) ? ' checked="checked"' : ''; ?> />
                                <label for="IsInternal-1"><?php echo $this->translate('dialog_form_node_link_is_internal'); ?></label>
                            </div>
                            <div>
                                <input type="radio" id="IsInternal-0" name="IsInternal" value="0"<?php echo ($isUpdating && !$this->NodeParameter['IsInternal']) ? ' checked="checked"' : ''; ?> />
                                <label for="IsInternal-0"><?php echo $this->translate('dialog_form_node_link_is_external'); ?></label>
                            </div>
                        </td>
                        <td>
                            <input type="hidden" name="LinkedNodeId" value="<?php echo $linkedNodeId; ?>" />
                            <div class="IsInternal-1">
                                <div class="description tips"><?php echo $this->translate('dialog_form_node_link_description_query_internals'); ?></div>
                                <input type="text" id="QueryNodes"<?php echo $queryNodeLabel; ?> />
                            </div>
                            <div class="IsInternal-0">
                                <div class="description tips"><?php echo $this->translate('dialog_form_node_link_description_query_externals'); ?></div>
                                <label for="TreeList" class="block">
                                    <?php echo $this->translate('dialog_form_node_link_external_tree_list'); ?>
                                </label>
                                <select id="TreeList">
                                    <option value=""><?php echo $this->translate('dialog_form_node_link_external_tree_list_option_default'); ?></option>
                                    <?php 
                                        foreach($this->SubTrees as $treeInfo) {
                                            $rootNodeId = $treeInfo['RootNodeId'];
                                            if (is_null($rootNodeId)) {
                                                continue;
                                            }
                                            echo '<option value="', $rootNodeId, '"';
                                            if ($isUpdating && $linkedNodeId == $rootNodeId) {
                                                echo ' selected="selected"';
                                            }
                                            echo '>', $treeInfo['Label'], '</option>', PHP_EOL;
                                        } 
                                    ?>
                                </select>
                            </div>
                        </td>
                    </tr>
                </table>
                <?php if ($isUpdating) : ?>
                <input type="hidden" name="NodeParamLinkId" value="<?php echo $this->NodeParameter['NodeParamLinkId']; ?>" />
                <?php endif; ?>
                <div class="dialog-button">
                    <span><button type="submit" id="ok"><?php echo $this->translate('application_handler_ok')?></button></span>
                </div>
            </div>
        </div>
    </form>
</div>
<?php
/* EOF */