<?php
/**
 * $Rev: 2390 $
 * $LastChangedDate: 2010-06-02 17:40:19 +0800 (Wed, 02 Jun 2010) $
 * $LastChangedBy: junzhang $
 *
 * @category   application
 * @package    modules_default
 * @subpackage view_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */

/**
 * response for update output
 */
// Disabled layout
$this->layout()->disableLayout();
?>

<div class="notification"
<?php
foreach($this->OutputInfo as $key=>$value) {
    echo $key . '="' . $value . '" ';
}
?>
><?php echo $this->translate('node_output_is_updated');?></div>

<?php
/* EOF */