<?php
/**
 * $Rev: 1746 $
 * $LastChangedDate: 2010-03-23 18:46:26 +0800 (Tue, 23 Mar 2010) $
 * $LastChangedBy: zwang $
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id: index.phtml 1746 2010-03-23 10:46:26Z zwang $
 */

$baseUrl = rtrim($this->BaseUrl(), '/');

$this->headLink()->appendStylesheet($baseUrl . '/styles/jquery-tablesorter.css')
                 ->appendStylesheet($baseUrl . '/styles/resource.css')
                 ->appendStylesheet($baseUrl . '/styles/number.css');
$this->headScript()->appendFile($baseUrl . '/js/jquery-metadata.js')
                   ->appendFile($baseUrl . '/js/jquery-tablesorter.js')
                   ->appendFile($baseUrl . '/js/resource.js')
                   ->appendFile($baseUrl . '/js/number.js');
if ($this->IsSuperAdmin) {
?>
    <div class="grid_2 prefix_1 oops-container">
        <div id="left_menu" class="left_menu">
            <a href="<?php echo $baseUrl?>/number/list" class="list-refresh sw-button on">
                <?php echo $this->translate('left_menu_number')?>
            </a>
            <a href="<?php echo $baseUrl?>/number/create" class="sw-button only-popup" id="create">
                <?php echo $this->translate('left_menu_add_number')?>
            </a>
        </div>
    </div>
<?php } ?>
<div class="grid_12 suffix_1 oops-container<?php echo $this->IsSuperAdmin ? '' : ' prefix_2';?>">
    <div id="numbers" class="list-container">
        <div class="list-content">
            <table>
                <tbody>
                    <tr>
                        <td>
                            <div class="list-header">
                                <table>
                                    <tbody>
                                        <tr>
                                            <td>
                                                <?php if ($this->IsSuperAdmin) { ?>
                                                    <div class="list-header-below"><span class="icon-below">&nbsp;</span></div>
                                                    <div class="list-header-batch-delete">
                                                        <button type="button" id="delete" class="batch-delete">
                                                        <?php echo $this->translate('application_handler_batch_delete')?>
                                                        </button>
                                                    </div>
                                                <?php } ?>
                                                <div class="search-box" >
                                                    <form action="<?php echo $baseUrl, '/number/list'?>">
                                                        <div class="search-box-input">
                                                            <div class="search-icon">&nbsp;</div>
                                                            <input type="text" name="PremiumNumberUiPart" class="keyword input_default"
                                                            value="<?php echo $this->translate('application_handler_search_input')?>"/>
                                                        </div>
                                                        <button class="search" type="submit">
                                                        <?php echo $this->translate('application_handler_ok')?></button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div id="number-list" class="list-body">
                                <table>
                                    <thead>
                                        <tr>
                                            <?php if ($this->IsSuperAdmin) { ?>
                                                <th class="column-1"><div><input type="checkbox" class="checkbox-switch"/></div></th>
                                            <?php } ?>
                                                <th class="column-2" title="<?php echo $this->translate('number_list_customer_number')?>">
                                                    <span><?php echo $this->translate('number_list_customer_number')?></span>
                                                </th>
                                            <?php if ($this->IsSuperAdmin) { ?>
                                                <th class="column-3" title="<?php echo $this->translate('number_list_customer_name')?>">
                                                    <span><?php echo $this->translate('number_list_customer_name')?></span>
                                                </th>
                                                <th class="column-4" title="<?php echo $this->translate('number_list_system_number')?>">
                                                    <span><?php echo $this->translate('number_list_system_number')?></span>
                                                </th>
                                                <th class="column-5" title="<?php echo $this->translate('number_list_max_call_duration')?>">
                                                    <span><?php echo $this->translate('number_list_max_call_duration')?></span>
                                                </th>
                                            <?php } ?>
                                            <th class="column-6" title="<?php echo $this->translate('number_list_solution')?>">
                                                <span><?php echo $this->translate('number_list_solution')?></span>
                                            </th>
                                            <th class="column-0" title="<?php echo $this->translate('number_list_templete_name')?>">
                                                <span><?php echo $this->translate('number_list_templete_name')?></span>
                                            </th>
                                            <?php if (! $this->IsSuperAdmin) { ?>
                                                <th class="column-7" title="<?php echo $this->translate('number_list_assignment')?>">
                                                    <span><?php echo $this->translate('number_list_assignment')?></span>
                                                </th>
                                                <th class="column-8" title="<?php echo $this->translate('number_list_date_created')?>">
                                                    <span><?php echo $this->translate('number_list_date_created')?></span>
                                                </th>
                                            <?php } ?>
                                        </tr>
                                    </thead>
                                    <?php
                                        echo $this->render('number/list.phtml');
                                    ?>
                                </table>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
var LOCAL = "<?php echo $baseUrl, '/number/'?>";
</script>
<?php
/* EOF */