<?php
#####################################################################################
##                                                                                 ##
##                    This file is generated by yeahEasy! system                   ##
##                                                                                 ##
##                               http://www.itnoon.com                             ##
##                              http://www.kinful.com                            ##
##                                Copyright@itnoon.com                             ##
##                                                                                 ##
##                                  Author:Wangkilin                               ##
##                                  wangkilin@126.com                              ##
##                 If you find any bug,please email me.Thank you!                  ##
##                               Let's do a better work!                           ##
#####################################################################################
$_system["config"]["allow_register"]              =	 "1";
$_system["config"]["is_count_ip"]                 =	 "1";
$_system["config"]["count_admin_ip"]              =	 "0";
$_system["config"]["record_admin_sql"]            =	 "y";
$_system["config"]["session_cache_expire"]        =	 "180";
$_system["config"]["position_in_file"]            =	 "0";
$_system["config"]["block_in_file"]               =	 "0";
$_system["config"]["site_name"]                   =	 "cet.kinful.com";
$_system["config"]["register_email_unique"]       =	 "1";
$_system["config"]["admin_activity_user"]         =	 "1";
$_system["config"]["default_language"]            =	 "cn";
$_system["config"]["db_int_seperator"]            =	 ",";
$_system["config"]["module_in_file"]              =	 "0";
$_system["config"]["default_theme"]               =	 "kinful";
$_system["config"]["component_in_file"]           =	 "0";
$_system["config"]["menu_in_file"]                =	 "0";
$_system["config"]["admin_theme"]                 =	 "2";
$_system["config"]["database_type"]               =	 "mysql,pgsql,mssql,oracle";
?>
