<?php
/**
 * $Rev: 2544 $
 * $LastChangedDate: 2010-06-12 18:29:57 +0800 (Sat, 12 Jun 2010) $
 * $LastChangedBy: junzhang $
 *
 * @category   application
 * @package    modules_default
 * @subpackage views_scripts_tree
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     James ZHANG <junzhang@streamwide.com>
 * @version    $Id: copy.phtml 2544 2010-06-12 10:29:57Z junzhang $
 */

// Do nothing, if needs open a modal window
$this->layout()->disableLayout();

/* EOF */