<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */

// Disabled layout
$this->layout()->disableLayout();
echo '<div class="notification">',
    $this->translate('application_msg_tree_is_created_ok', array($this->TreeLabel)),
    ' </div><table>',
    PHP_EOL,
    $this->Action('list', 'tree', null, array(
        'CustomerUserId' => $this->CustomerUserId,
        'CustomerAccountId' => $this->CustomerAccountId,
        'CurrentPage' => $this->Pagination['CurrentPage'],
        'ItemsPerPage' => $this->Pagination['ItemsPerPage'],
    )), '</table>';

/* EOF */