<?php
/**
 * $Rev: 2544 $
 * $LastChangedDate: 2010-06-12 18:29:57 +0800 (Sat, 12 Jun 2010) $
 * $LastChangedBy: junzhang $
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id: update-ack.phtml 2544 2010-06-12 10:29:57Z junzhang $
 */

// Disabled layout
$this->layout()->disableLayout();

//TODO: calling by builder action

/* EOF */