<?php
/**
 * $Rev: 1974 $
 * $LastChangedDate: 2010-04-08 12:50:29 +0800 (Thu, 08 Apr 2010) $
 * $LastChangedBy: yaoli $
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id: list.phtml 1974 2010-04-08 04:50:29Z yaoli $
 */

$baseUrl = rtrim($this->BaseUrl(), '/') . '/contact';

?>
<div class="notification"><?php echo $this->translate('contact_export_file');?></div>
<?php
/* EOF */