<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */

// Disabled layout
$this->layout()->disableLayout();
$baseUrl = rtrim($this->BaseUrl(), '/') . '/contact';
?>
<div class="notification"><?php echo $this->translate('contact_is_updated', $this->Contact['ContactName']);?></div>
<table>
    <tr>
        <td class="column-1">
            <input type="checkbox" name="contact_list[]" value="<?php echo $this->Contact['ContactId']?>"/></p>
        </td>
        <td class="column-2">
            <span><?php echo $this->Contact['ContactName']?></span>
            <div class="manager">
                <a class="manager-edit" href="<?php echo $baseUrl?>/update/ContactId/<?php echo $this->Contact['ContactId']?>">
                    <?php echo $this->translate('application_handler_edit')?>
                </a> | <a class="manager-delete" href="<?php echo $baseUrl?>/delete?ContactIds[]=<?php echo $this->Contact['ContactId']?>&ContactNames[]=<?php
                    echo urlencode($this->Contact['ContactName'])?>"><?php echo $this->translate('application_handler_delete')?>
                </a>
            </div>
        </td>
        <td class="column-3" title="">
            <span><?php echo $this->Contact['ContactPhone']?></span>
        </td>
        <td class="column-4" title="">
            <span><?php echo $this->Contact['CreationDatetime']?></span>
        </td>
        <td class="column-5" title="">
            <span><?php echo $this->Contact['ModificationDatetime']?></span>
        </td>
        <td class="column-6" title="">
            <span><?php echo $this->Contact['CustomerUserName']?></span>
        </td>
        <td class="column-0" title="">
            <i class="resource_<?php echo ($this->Contact['ReferenceCounter']>0 ? 'in':'not')?>_use"><?php echo $this->Contact['ReferenceCounter']?></i>
        </td>
    </tr>
</table>
<?php
/* EOF */