<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */

// Disabled layout
$this->layout()->disableLayout();
$baseUrl = rtrim($this->BaseUrl(), '/') . '/origingroup';
?>
<div class="notification"><?php echo $this->translate('origingroup_is_updated', $this->OriginGroup['OriginGroupName']);?></div>
<table>
    <tr>
        <td class="column-1">
            <input type="checkbox" name="origingroup_list[]" value="<?php echo $this->OriginGroup['OriginGroupId']?>"/></p>
        </td>
        <td class="column-2">
            <span><?php echo $this->OriginGroup['OriginGroupName']?></span>
            <div class="manager">
                <a class="manager-edit" href="<?php echo $baseUrl?>/update/OriginGroupId/<?php echo $this->OriginGroup['OriginGroupId']?>">
                    <?php echo $this->translate('application_handler_edit')?>
                </a> | <a class="manager-delete" href="<?php echo $baseUrl?>/delete?OriginGroupIds[]=<?php echo $this->OriginGroup['OriginGroupId']?>&OriginGroupLabels[]=<?php
                    echo urlencode($this->OriginGroup['OriginGroupName'])?>"><?php echo $this->translate('application_handler_delete')?>
                </a>
            </div>
        </td>
        <td class="column-3" title="">
            <span><?php echo $this->OriginGroup['OriginGroupId']?></span>
        </td>
    </tr>
</table>
<?php
/* EOF */