<?php
/**
 * $Rev$
 * $LastChangedDate$
 * $LastChangedBy$
 *
 * @category   application
 * @package    layouts_scripts
 * @copyright  Copyright (c) 2010 Streamwide SAS
 * @author     Kilin WANG <zwang@streamwide.com>
 * @version    $Id$
 */

$baseUrl = rtrim($this->BaseUrl(), '/') . '/origin';
// Disabled layout
$this->layout()->disableLayout();
$heading = '<div id="origin-heading" class="dialog-heading"><span class="heading-text">'
    . $this->translate('origin_create_origin') . '</span><span class="heading-close">×</span></div>';

// prepare origins by group
foreach($this->SystemOrigins as $systemOrigin)
{
	$_tmpGroupName = '___' . $systemOrigin['OriginGroupId'] . '_' . $systemOrigin['OriginGroupName'];
	if (!isset($$_tmpGroupName)) {
		$$_tmpGroupName = '';
	}

	$$_tmpGroupName .= '<dd>' . $systemOrigin['OriginName']
	                       . '<input type="hidden" class="origin_item" name="SysOriginIds[]" value="' . $systemOrigin['OriginId'] . '">'
	                 . '</dd>';
}


// prepare origin groups
$originGroups = $originGroupOptions = '';
foreach($this->OriginGroups as $group) {
	$originGroups .= '<dl id="group_' . $group['OriginGroupId'] . '" class="collapse">'
	               . '<dt><i>icon</i><u>' . $group['OriginGroupName'] . '</u></dt>';
	$_tmpGroupName = '___' . $group['OriginGroupId'] . '_' . $group['OriginGroupName'];
	if (isset($$_tmpGroupName)) {
		$originGroups .= $$_tmpGroupName;
	}

	$originGroups .= '</dl>';

	$originGroupOptions .= '<option value="' . $group['OriginGroupId'] .'">' . $group['OriginGroupName'] . '</option>';
}


$body = '<p id="zone_origin_label">'
           . '<label>' . $this->translate('origin_input_name') . '</label>'
           . '<br>'
           . '<input type="text" name="Label" value=""/>'
           . '<i>' . $this->translate('origin_name_description') . '</i>'
      . '</p>'

      .(
       $this->CustomerAccountId?
       '' : ('<p id="zone_origin_group">'
           . '<label>' . $this->translate('origin_origin_group') . '</label>'
           . '<br>'
           . '<select name="OriginGroupId">'
           //. '<option value="">' . $this->translate('origin_select_origin_group') . '</option>'
           . $originGroupOptions
           . '</select>'
      . '</p>')
      )


      . '<p id="zone_origin_list_explain">'
           . '<i>' . $this->translate('origin_list_explain') . '</i>'
      . '</p>'

      . '<table>'
      . '<tr>'
      . '<td id="zone_system_origin_list">'
      . '<label>' . $this->translate('origin_predefined_list') . '</label>'
      . '<div id="system_origin_list">'
           . $originGroups
      . '</div>'
      . '<p id="zone_phone_prefix">'
           . '<label>' . $this->translate('origin_type_prefix') . '</label>'
           . '<br>'
           . '<input type="text" id="phone_prefix" name="prefix" value=""/>'
      . '</p>'
      . '</td>'

      . '<td id="zone_button_container">'
      . '<button class="right_arrow" id="go_right">-&gt;</button>'
      . '<button class="left_arrow" id="go_left">&lt;-</button>'
      . '<button class="right_arrow" id="add_prefix">-&gt;</button>'
      . '</td>'

      . '<td id="zone_user_origin_list">'
      . '<label>' . $this->translate('origin_defined_list') . '</label>'
      . '<div id="user_origin_list">'
           . '<dl id="user_prefix_list">'
           . '<dt>'
           . $this->translate('origin_phone_prefix')
           . '</dt>'
           . '</dl>'
      . '</div>'
      . '</td>'

      . '</tr>'

      . '</table>'

      . '<div class="clear"/>'

      . '<div class="middle_button_zone">'
      .    '<span>'
      .        '<button id="create_button">' . $this->translate('application_handler_ok') . '</button>'
      .    '</span>'
      . '</div>'

        ;

echo '<div class="dialog"><div class="dialog-content">' . $heading . '<div id="origin-body" class="dialog-body">' .
    $this->Form('create-origin-form',
        array(
            'method' => Zend_Form::METHOD_POST,
            'enctype' => Zend_Form::ENCTYPE_URLENCODED,
            'action'  => $baseUrl . '/create',
        ), $body)
    . '</div></div></div>'
    ;

/* EOF */