 <%  
Dim nongliyu(12)
nongliyu(1)="正"
nongliyu(2)="二"
nongliyu(3)="三"
nongliyu(4)="四"
nongliyu(5)="五"
nongliyu(6)="六"
nongliyu(7)="七"
nongliyu(8)="八"
nongliyu(9)="九"
nongliyu(10)="十"
nongliyu(11)="十一"
nongliyu(12)="十二"

Dim nongliri(31)
nongliri(1)="初一"
nongliri(2)="初二"
nongliri(3)="初三"
nongliri(4)="初四"
nongliri(5)="初五"
nongliri(6)="初六"
nongliri(7)="初七"
nongliri(8)="初八"
nongliri(9)="初九"
nongliri(10)="十"
nongliri(11)="十一"
nongliri(12)="十二"
nongliri(13)="十三"
nongliri(14)="十四"
nongliri(15)="十五"
nongliri(16)="十六"
nongliri(17)="十七"
nongliri(18)="十八"
nongliri(19)="十九"
nongliri(20)="二十"
nongliri(21)="二十一"
nongliri(22)="二十二"
nongliri(23)="二十三"
nongliri(24)="二十四"
nongliri(25)="二十五"
nongliri(26)="二十六"
nongliri(27)="二十七"
nongliri(28)="二十八"
nongliri(29)="二十九"
nongliri(30)="三十"
nongliri(31)="三十一"
%> 








